name: Deploy Salesforce Metadata

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/core.yml
    with:
      mode: deploy
      environment: ${{ github.ref_name == 'main' && 'Production' || 'Non-Production' }}
    secrets: inherit
