name: Validate Salesforce Deployment

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/core.yml
    with:
      mode: validate
      environment: ${{ github.base_ref == 'main' && 'prod' || 'nonprod' }}
    secrets: inherit
