name: Validate Salesforce Deployment

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/core.yml
    permissions:
      contents: write
    with:
      mode: validate
      environment: ${{ github.ref_name == 'main' && 'Production' || 'Non-Production' }}
    secrets: inherit
